# Generated by Django 2.1.4 on 2020-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToExamine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('committerInformation', models.TextField(default='none', verbose_name='qq或微信')),
                ('committerUrl', models.TextField(default='none', verbose_name='贴子链接')),
                ('reportQq', models.TextField(default='none', verbose_name='QQ')),
                ('reportVx', models.TextField(default='none', verbose_name='微信')),
                ('reportSteam', models.TextField(default='none', verbose_name='steamid')),
                ('reportAliPay', models.TextField(default='none', verbose_name='支付宝账号')),
                ('reportMaxId', models.TextField(default='none', verbose_name='max+账号')),
                ('reportHeiBox', models.TextField(default='none', verbose_name='小黑盒账号')),
                ('reportTieBa', models.TextField(default='none', verbose_name='贴吧账号')),
                ('examineFlag', models.TextField(default='0', verbose_name='是否审核')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportQq', models.TextField(default='none', verbose_name='QQ')),
                ('reportVx', models.TextField(default='none', verbose_name='微信')),
                ('reportSteam', models.TextField(default='none', verbose_name='steamid')),
                ('reportAliPay', models.TextField(default='none', verbose_name='支付宝账号')),
                ('reportMaxId', models.TextField(default='none', verbose_name='max+账号')),
                ('reportHeiBox', models.TextField(default='none', verbose_name='小黑盒账号')),
                ('reportTieBa', models.TextField(default='none', verbose_name='贴吧账号')),
                ('reportUrl', models.TextField(default='none', verbose_name='贴子链接')),
            ],
        ),
    ]
