# Generated by Django 3.1 on 2020-08-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200819_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='delete',
            field=models.TextField(default='0', verbose_name='是否被删除'),
        ),
    ]
