# Generated by Django 3.1 on 2020-08-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200819_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('visits', models.IntegerField(default=0, verbose_name='访问次数')),
                ('search', models.IntegerField(default=0, verbose_name='搜索次数')),
                ('allrecord', models.IntegerField(default=0, verbose_name='登记数量')),
                ('upload', models.IntegerField(default=0, verbose_name='上传次数')),
            ],
        ),
    ]
