# Generated by Django 3.1 on 2020-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('user', models.TextField(default='none', verbose_name='账号')),
                ('password', models.TextField(default='none', verbose_name='密码')),
            ],
        ),
    ]
