# Generated by Django 3.1 on 2020-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('aimId', models.CharField(default='none', max_length=255, verbose_name='审核图片关联id')),
                ('imgFile', models.ImageField(blank=True, null=True, upload_to='checkImg', verbose_name='审核图片')),
            ],
        ),
    ]
