# Generated by Django 3.1 on 2020-08-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200824_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examineimg',
            name='examine',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.toexamine', verbose_name='该图片所属信息'),
        ),
    ]
