# Generated by Django 3.1 on 2020-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200824_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('name', models.TextField(default='none', verbose_name='名称')),
                ('thanksUrl', models.TextField(default='none', verbose_name='赞助者链接')),
            ],
        ),
    ]
