# Generated by Django 3.1 on 2020-09-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200926_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('content', models.TextField(default='none', verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('title', models.TextField(default='none', verbose_name='标题')),
                ('content', models.TextField(default='none', verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('name', models.TextField(default='none', verbose_name='账号')),
                ('email', models.TextField(default='none', verbose_name='账号')),
                ('password', models.TextField(default='none', verbose_name='密码')),
            ],
        ),
        migrations.DeleteModel(
            name='Manage',
        ),
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.TextField(default='none', verbose_name='走失者-性别'),
        ),
        migrations.AlterField(
            model_name='people',
            name='timeL',
            field=models.TextField(default='none$none$none$none$none', verbose_name='走失者-走失日期'),
        ),
        migrations.AddField(
            model_name='news',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user', verbose_name='消息所属用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='newLink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.news', verbose_name='评论所属消息'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user', verbose_name='评论所属用户'),
        ),
    ]
