# Generated by Django 3.1 on 2020-09-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200927_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('imgFile', models.ImageField(blank=True, null=True, upload_to='checkImg', verbose_name='消息图片')),
                ('oneNews', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.news', verbose_name='该图片所属信息')),
            ],
        ),
    ]
