# Generated by Django 3.1 on 2020-09-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_newsimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(default='none', verbose_name='邮箱'),
        ),
    ]
