# Generated by Django 3.1 on 2020-09-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200928_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一id')),
                ('visits', models.IntegerField(default=0, verbose_name='访问次数')),
                ('search', models.IntegerField(default=0, verbose_name='搜索次数')),
                ('upload', models.IntegerField(default=0, verbose_name='上传次数')),
            ],
        ),
    ]
